version: '3'
services:
  node:
    image: landscapedatacommons/jornada-ejs:1.0.0 
    ports:
      - 80:5000
    deploy:
      replicas: 2
      update_config:
        parallelism: 1

        failure_action: rollback
        delay: 20s
      
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s